os:
    - linux

language: python
python:
    - 2.7
    - pypy
    - 3.3
    - 3.4

install:
    - python setup.py install

env:
    - TRAVIS_CI=TRAVIS_CI

script:
    - python -m unittest discover
    - bgmi -h
    - bgmi cal all
    - bgmi add "Re：從零開始的異世界生活" "NEW GAME!" "天真與閃電" "食戟之靈 貳之皿"
    - bgmi update
    - bgmi delete --name "食戟之靈 貳之皿"
    - bgmi delete --clear-all --batch
    - bgmi add "Re：從零開始的異世界生活"
    - bgmi cal followed
    - bgmi config --name MAX_PAGE --value 3
    - bgmi download --list
    - bgmi add "Rewrite" "天真與閃電"
    - bgmi followed --mark Rewrite --episode 0
    - bgmi mark Rewrite 1
    - bgmi update "Rewrite" "天真與閃電"
    - bgmi filter "Rewrite" --subtitle "愛戀,星岡,千夏" --include "简体" --exclude "720p,720P"
    - bgmi fetch "Rewrite"
