os:
    - linux

language: python
python:
    - 2.7
    - pypy
    - 3.3
    - 3.4

install:
    - python setup.py install

env:
    - TRAVIS_CI=23333

script:
    - python -m unittest discover
    - bgmi
    - bgmi cal all
    - bgmi add "Re：從零開始的異世界生活" "NEW GAME!" "天真與閃電" "食戟之靈 貳之皿"
    - bgmi update
    - bgmi delete --name "食戟之靈 貳之皿"
    - bgmi delete --clear-all --batch
    - bgmi add "Re：從零開始的異世界生活"
    - bgmi cal followed
    - bgmi filter "Re：從零開始的異世界生活" "惡魔島,DHR"
    - bgmi filter "Re：從零開始的異世界生活" "DHR" --remove
    - bgmi config MAX_PAGE 3
    - bgmi fetch "Re：從零開始的異世界生活"
    - bgmi filter "Re：從零開始的異世界生活" --remove-all
    - bgmi download list
    - bgmi add "Rewrite" "天真與閃電"
    - bgmi mark Rewrite 0
    - bgmi update --name "Rewrite" "天真與閃電"
