os:
    - linux

language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.6

install:
    - python setup.py install

env:
    - TRAVIS_CI=TRAVIS_CI

script:
    - export BANGUMI_1=捏造陷阱NTR
    - export BANGUMI_2=骑士魔法
    - export BANGUMI_3=异世界食堂
    - python -m unittest discover
    - bgmi -h
    - bgmi cal
    - bgmi config DOWNLOAD_DELEGATE 'rr!'
    - bgmi add $BANGUMI_1 $BANGUMI_2 $BANGUMI_3
    - bgmi update
    - bgmi delete --name $BANGUMI_3
    - bgmi delete --clear-all --batch
    - bgmi add $BANGUMI_2 --episode 1
    - bgmi list
    - bgmi config ARIA2_RPC_TOKEN 'token:233'
    - bgmi download --list
    - bgmi mark $BANGUMI_2 1
    - bgmi update $BANGUMI_2
    - bgmi filter $BANGUMI_2 --subtitle "" --exclude "MKV" --regex "720p|720P"
    - bgmi fetch $BANGUMI_2
    - bgmi search "为美好的世界献上祝福！" --regex-filter '.*动漫国字幕组.*为美好的世界献上祝福！].*720P.*'
