os:
    - linux
    - os x

language: python
python:
    - 2.7
    - pypy
    - 3.2
    - 3.3
    - 3.4

install:
    - python setup.py install

script:
    - python -m unittest discover
    - bgmi cal all
    - bgmi add "Re：從零開始的異世界生活" "暗殺教室Ⅱ" "線上遊戲的老婆不可能是女生？" "在下坂本，有何貴幹？" "JoJo的奇妙冒險 不滅鑽石"
    - bgmi update
    - bgmi delete --name "暗殺教室Ⅱ"
    - bgmi delete --clear-all --batch
    - bgmi cal followed

matrix:
  exclude:
  - python: '2.6'
    script: 'python -m unittest discover'