os:
    - linux

language: python
python:
    - 2.7
    - pypy
    - 3.3
    - 3.4

install:
    - python setup.py install

env:
    - TRAVIS_CI=TRAVIS_CI

script:
    - python -m unittest discover
    - bgmi -h
    - bgmi cal all
    - bgmi config DOWNLOAD_DELEGATE 'rr!'
    - bgmi add "雏子的笔记" "Re:CREATORS" "我的妹妹是工口漫画老师"
    - bgmi update
    - bgmi delete --name "我的妹妹是工口漫画老师"
    - bgmi delete --clear-all --batch
    - bgmi add "我的妹妹是工口漫画老师" --episode 1
    - bgmi cal followed
    - bgmi config ARIA2_RPC_TOKEN 'token:233'
    - bgmi download --list
    - bgmi followed --mark "我的妹妹是工口漫画老师" --episode 0
    - bgmi mark "我的妹妹是工口漫画老师" 1
    - bgmi update "我的妹妹是工口漫画老师"
    - bgmi filter "我的妹妹是工口漫画老师" --subtitle "RH字幕組,動漫國字幕組,LoliHouse" --exclude "MKV" --regex "720p|720P"
    - bgmi fetch "我的妹妹是工口漫画老师"
