os:
    - linux
    - os x

language: python
python:
    - 2.7
    - pypy
    - 3.2
    - 3.3
    - 3.4

install:
    - python setup.py install

script:
    - python -m unittest discover
    - bgmi
    - bgmi cal all
    - bgmi add "Re：從零開始的異世界生活" "暗殺教室Ⅱ" "線上遊戲的老婆不可能是女生？" "在下坂本，有何貴幹？" "JoJo的奇妙冒險 不滅鑽石"
    - bgmi update
    - bgmi delete --name "暗殺教室Ⅱ"
    - bgmi delete --clear-all --batch
    - bgmi cal followed
    - bgmi add "在下坂本，有何貴幹？"
    - bgmi filter "在下坂本，有何貴幹？" "動漫國,KNA,悠哈C9"
    - bgmi filter "在下坂本，有何貴幹？" "KNA,悠哈C9" --remove
    - bgmi config MAX_PAGE 3
    - bgmi fetch "在下坂本，有何貴幹？"
    - bgmi filter "在下坂本，有何貴幹？" --remove-all
